- name: Install and start the file servers
  yum:
    name:
    - "{{ ansible_local.custom_fact.packages.smb_package }}"
    - "{{ ansible_local.custom_fact.packages.ftp_package }}"
    state: latest
- name: start samba server
  service:
    name: "{{ ansible_local.custom_fact.services.smb_service }}"
    state: started
    enabled: true
- name: start ftp server
  service: 
    name: "{{ ansible_local.custom_fact.services.ftp_service }}"
    state: started
    enabled: true

    
