- name: Install and start the servers
  yum:
    name:
    - "{{ ansible_local.custom_fact.packages.db_package }}"
    - "{{ ansible_local.custom_fact.packages.web_package }}"
    state: latest
- name: start DB server
  service:
    name: "{{ ansible_local.custom_fact.services.db_service }}"
    state: started
    enabled: true
- name: start web server
  service:
    name: "{{ ansible_local.custom_fact.services.web_service }}"
    state: started
    enabled: true
