- name: setting up httpd
  hosts: node1.testing.com
  force_handlers: True
  tasks:
    - name: Installing httpd
      yum:
        name: httpd
        state: installed
    - name: copy files
      copy:
        src: /tmp/index.html
        dest: /var/www/http/index.html
      notify:
        - restart_httpd
    - name: This task is wron one
      file:
        content: "wrong file which has no path"
        dest: /home/hemanthi/nofile.txt
        
  handlers:
    - name: restart_httpd
      service:
        name: httpd
        state: restarted
