- name: This is error handling
  hosts: node1.testing.com
  tasks:
    - block:
      - name: Upgrade the database
        shell:
          cmd: /usr/local/lib/upgrade-database
      rescue: 
      - name: revert after failure
        shell:
          cmd: /usr/local/lib/revert-database  
      always:
      - name: alway restart the database
        service:
          name: mariadb
          state: restarted

