- name: Working with tags
  hosts: node1.example.com
  tasks:
  - name: Install net packs
    package:
      name: "{{ item }"
      state: installed
    with_items:
      - nmap
      - wireshark
    tags:
      - net_analysis

  - name: Install lamp packages
    package:
      name: "{{ item }}"
      state: installed
    with_items: 
      - maria_db
      - httpd
    tags:
      - lamp_packages
