- hosts: node1.testing.com
  tasks:
    - name: Check mariadb status
      command: /usr/bin/systemctl is-active mariadb
      ignore_errors: yes
      register: result
    - name: Install http if mariadb is active
      yum:
    name: httpd
      state: installed
      when: result.rc == 0

    - name: start httpd
      service:
        name: httpd
        state: started
