- hosts: node1.testing.com
  tasks:
  - name: Installing package manager
    yum:
      name: openstack-packstack
      state: latest
    register: result

  - name: Generates answers file if packstack is installed
    command:
      packstack --gen-answer-file /root/hemanthansible.txt
    when: result.rc == 0
