- name: Install remote facts
  hosts: all
  vars:
    remote_dir: /etc/ansible/fact.d
    facts_file: custom_fact
  tasks:
  - name: Create remote directory
    file:
      state: directory
      recurse: yes
      path: "{{ remote_dir }}"
  - name: Install new facts
    copy:
      src: "{{ facts_file }}"
      dest: "{{ remote_dir }}"
...
